"""revert last migration

Revision ID: 3bd88ef231cf
Revises: d063aed7a917
Create Date: 2025-05-28 19:49:50.610062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bd88ef231cf"
down_revision: Union[str, None] = "d063aed7a917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "whatsapp_messages", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "whatsapp_messages", sa.Column("thread_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "whatsapp_messages", "whatsapp_threads", ["thread_id"], ["id"]
    )
    op.create_foreign_key(
        None, "whatsapp_messages", "whatsapp_users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "whatsapp_messages", type_="foreignkey")
    op.drop_constraint(None, "whatsapp_messages", type_="foreignkey")
    op.drop_column("whatsapp_messages", "thread_id")
    op.drop_column("whatsapp_messages", "user_id")
    # ### end Alembic commands ###
