"""embeddings_documents_table

Revision ID: 508d5d376b71
Revises: aec45d8e0551
Create Date: 2025-05-01 15:04:47.576147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "508d5d376b71"
down_revision: Union[str, None] = "aec45d8e0551"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("embedding", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "embedding")
    # ### end Alembic commands ###
