"""Add multi-number support

Revision ID: 789aa8f4f68f
Revises: bafea4bca805
Create Date: 2025-11-22 22:33:41.255815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '789aa8f4f68f'
down_revision: Union[str, None] = 'bafea4bca805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('twilio_subaccount_sid', sa.String(), nullable=False),
    sa.Column('twilio_auth_token', sa.String(), nullable=False),
    sa.Column('waba_id', sa.String(), nullable=True),
    sa.Column('meta_business_portfolio_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'failed', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_code'), 'whatsapp_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_whatsapp_accounts_id'), 'whatsapp_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_organization_id'), 'whatsapp_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_twilio_subaccount_sid'), 'whatsapp_accounts', ['twilio_subaccount_sid'], unique=True)
    op.create_index(op.f('ix_whatsapp_accounts_waba_id'), 'whatsapp_accounts', ['waba_id'], unique=False)
    op.create_table('whatsapp_phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('whatsapp_account_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('sender_sid', sa.String(), nullable=True),
    sa.Column('messaging_service_sid', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('status_callback_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'failed', name='phonenumberstatus'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['whatsapp_account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_phone_numbers_code'), 'whatsapp_phone_numbers', ['code'], unique=True)
    op.create_index(op.f('ix_whatsapp_phone_numbers_id'), 'whatsapp_phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_phone_numbers_phone_number'), 'whatsapp_phone_numbers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_whatsapp_phone_numbers_sender_sid'), 'whatsapp_phone_numbers', ['sender_sid'], unique=False)
    op.create_index(op.f('ix_whatsapp_phone_numbers_whatsapp_account_id'), 'whatsapp_phone_numbers', ['whatsapp_account_id'], unique=False)
    op.drop_column('whatsapp_users', 'account_sid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_users', sa.Column('account_sid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_whatsapp_phone_numbers_whatsapp_account_id'), table_name='whatsapp_phone_numbers')
    op.drop_index(op.f('ix_whatsapp_phone_numbers_sender_sid'), table_name='whatsapp_phone_numbers')
    op.drop_index(op.f('ix_whatsapp_phone_numbers_phone_number'), table_name='whatsapp_phone_numbers')
    op.drop_index(op.f('ix_whatsapp_phone_numbers_id'), table_name='whatsapp_phone_numbers')
    op.drop_index(op.f('ix_whatsapp_phone_numbers_code'), table_name='whatsapp_phone_numbers')
    op.drop_table('whatsapp_phone_numbers')
    op.drop_index(op.f('ix_whatsapp_accounts_waba_id'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_twilio_subaccount_sid'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_organization_id'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_id'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_code'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
