"""migrate whatsapp id to object

Revision ID: d063aed7a917
Revises: 5d86ac5718a7
Create Date: 2025-05-28 19:40:09.352667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d063aed7a917"
down_revision: Union[str, None] = "5d86ac5718a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "whatsapp_messages_thread_id_fkey", "whatsapp_messages", type_="foreignkey"
    )
    op.drop_constraint(
        "whatsapp_messages_user_id_fkey", "whatsapp_messages", type_="foreignkey"
    )
    op.drop_column("whatsapp_messages", "user_id")
    op.drop_column("whatsapp_messages", "thread_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "whatsapp_messages",
        sa.Column("thread_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "whatsapp_messages",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "whatsapp_messages_user_id_fkey",
        "whatsapp_messages",
        "whatsapp_users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "whatsapp_messages_thread_id_fkey",
        "whatsapp_messages",
        "whatsapp_threads",
        ["thread_id"],
        ["id"],
    )
    # ### end Alembic commands ###
