"""Change is_active column to Boolean type

Revision ID: f6d01eea92e7
Revises: dc13a5dc9020
Create Date: 2025-07-28 15:03:23.468810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f6d01eea92e7"
down_revision: Union[str, None] = "dc13a5dc9020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_credentials",
        "is_active",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="is_active::boolean",
    )
    op.add_column("whatsapp_messages", sa.Column("role", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("whatsapp_messages", "role")
    op.alter_column(
        "service_credentials",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
